name: Supabase Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/supabase-migrations.yml'

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_REF}}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Database Migrations
        run: |
          echo "Pushing database migrations to Supabase..."
          supabase db push
          
      - name: Verify Migration Deployment
        run: |
          echo "Verifying migration deployment..."
          supabase migration list

      - run: supabase functions deploy --project-ref $PROJECT_ID       
          
      - name: Deployment Summary
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Supabase deployment completed successfully!"
            echo "📊 Migrations deployed to: ${{ secrets.SUPABASE_PROJECT_REF }}"
          else
            echo "❌ Supabase deployment failed!"
            echo "Please check the logs above for more details."
            exit 1
          fi 
